add resnet 50 v1 in tf fp32 int8
AmpereComputingAI/ampere_model_library pull request #131
Opened 2022-05-23 10:48 UTC by MarcelWilnicki

2022-05-24 06:40 UTC, jangrzybek requested changes
Where to get those models? Please update the read-me.

2022-06-06 20:59 UTC, jan-grzybek-ampere approved these changes

2023-04-18 14:23 UTC, jan-grzybek-ampere reviewed
Do we have that resnet_50_v1 stored in S3?

2023-04-18 14:29 UTC, MarcelWilnicki commented
> Do we have that resnet_50_v1 stored in S3?

yes, in ampere ai model zoo bucket

2023-04-24 22:04 UTC, jan-grzybek-ampere requested changes

2023-04-24 22:04 UTC, jan-grzybek-ampere commented on computer_vision/classification/resnet_50_v1/run.py
> +                        choices=["tf", "pytorch", "ort"], required=True,
How to choose tflite? 😭

2023-04-26 11:45 UTC, jan-grzybek-ampere commented on computer_vision/classification/resnet_50_v1/run.py
> +            run_tflite_int8(**vars(args))
framework == "tf" but tflite is run

2023-05-15 22:04 UTC, jan-grzybek-ampere approved these changes

2023-05-18 13:29 UTC, merged