Add Segment Anything model + new utils
AmpereComputingAI/ampere_model_library pull request #174
Opened 2023-04-12 21:18 UTC by jan-grzybek-ampere

* SAM network
* wrapper for argparse
* some changes to COCO class to support segmentation task
* new PyTorchRunnerV2 class -> simplifies what PyTorchRunner did and shifts the responsibility for torch compilation to the user of the class (i.e. torch compilation of network's graph should take place in runner script of given network)

2023-04-14 13:27 UTC, MarcelWilnicki commented
where can I find the model?

2023-04-14 13:32 UTC, MarcelWilnicki commented
consider splitting it into individual PRs. PR per feature. This will make reviewing easier.

2023-04-14 13:46 UTC, jan-grzybek-ampere commented
> where can I find the model?

There is a read-me covering that

2023-04-18 14:25 UTC, jan-grzybek-ampere commented
@MarcelWilnicki do you have any comments aside from <python3.9 incompatibility?

2023-04-18 17:17 UTC, dkupnicki requested changes
Good PR, just a few small things

2023-04-18 17:17 UTC, dkupnicki commented on utils/pytorch.py
> +class PyTorchRunnerV2:
It's not that much different from V1. What's the plan here? Do we want to eventually move all of the models to use V2 and it's just a temporary measure to have both of them at the same time?

2023-04-18 20:19 UTC, smamindl commented on utils/helpers.py
> +    def __init__(self, supported_frameworks: list[str]):
I see the same issue - TypeError: 'type' object is not subscriptable

2023-04-26 17:26 UTC, jan-grzybek-ampere commented
@dkupnicki @MarcelWilnicki @smamindl I've addressed the issues, please have another look

2023-04-27 17:08 UTC, dkupnicki approved these changes
Looks good 👍

2023-05-04 20:05 UTC, merged